-- TODO incomplete query, need to verify how to compare against an array of values
-- select
--   type || ' ' || name as resource,
--   case
--     when (arguments ->> 'source_type') <> 'db-instance' then 'skip'
--     when (arguments ->> 'source_type') = 'db-instance' and (arguments -> 'enabled')::bool and (arguments -> 'event_categories_list') @> '["failure", "maintenance"]' then 'ok'
--     else 'alarm'
--   end as status,
--   case
--     when source_type <> 'db-instance' then cust_subscription_id || ' event subscription of ' || source_type || ' type.'
--     when source_type = 'db-instance' and enabled and event_categories_list @> '["failure", "maintenance"]' then cust_subscription_id || ' event subscription enabled for critical db cluster events.'
--     else cust_subscription_id || ' event subscription missing critical db cluster events.'
--   end || '.' as reason,
--   path
-- from
--   terraform_resource
-- where
--   type = 'aws_db_event_subscription';